### ISSUE TITLE
Feature Request: Create Unflat Function

### ISSUE THREAD

**Issue by jessie-codes** [jessie-codes/safe-flat#32]
**Is your feature request related to a problem? Please describe.**

This library currently only supports taking a nested object and flattening it. Ideally, it would also have a function that would take a flatten objected and return a nested object.

**Describe the solution you'd like**

Create a new function, `unflatten`, with a function signature of `(obj, delimiter)` which will return a nested version of the object.

**Additional context**

This will need to be a breaking change as the code exports the `flatten` function directly. The new version should export an object that has both the unflatten and flatten functions.

**Comment by rpartha** [comment]
I'll take this one. Please assign to me.

**Comment by jessie-codes** [comment]
Thanks for taking this on. I look forward to your PR. Please ensure to include unit tests that match the scenarios of the `flatten` function.

**Comment by rpartha** [comment]
Quick question. Let's say we use the below from your test case:
```js
const f= {
    'a.b.c': 'value',
    'a.b.d': '[Circular]',
    'a.b.e.g': 'value',
    'a.b.e.f': '[Circular]',
    'x.y.z': '[Circular]'
  }
```
How should I handle the `'[Circular]'` values? For example, you set `original.a.b.d = original.a` but that's not given here.

**Comment by jessie-codes** [comment]
Great question. I think you can just treat them as strings and it can be
noted within the docs, so given that object, the output of unflatten should
be:

{
  a: {
    b: {
      c: 'value',
      d: '[Circular]',
      e: {
        f: '[Circular]',
        g: 'value'
      }
    },
    x: {
      y: {
        z: '[Circular]'
      }
    }
  }
}

**Comment by rpartha** [comment]
Thanks for clarifying!
