### ISSUE TITLE
Also flattens cats 🐈

### ISSUE THREAD

**Issue by nikitaeverywhere** [jessie-codes/safe-flat#36]
Hello!

Did you consider this use case for your library? https://github.com/hughsk/flat/issues/118 What's the motivation behind flattening custom objects? This can give unexpected surprises like property-symbols or strange buffers. Thanks!

Tested on [RunKit](https://npm.runkit.com/safe-flat) for v2.0.0:

```javascript
const { flatten } = require("safe-flat")

class Cat {
  constructor() {
    this.name = 'Cosmonaut';
  }
  meow() {
    console.log('Meow.');
  }
}

result = flatten({
  cat: {
    instance: new Cat(),
  },
});

console.log(result);
console.log(result['cat.instance']?.meow());
```

Result:

```
Object {cat.instance.name: "Cosmonaut"}
undefined
```

See more in https://github.com/hughsk/flat/issues/118.

**Comment by jessie-codes** [comment]
@ZitRos I guess my question would be why would you pass an object you don't want to be flattened to a flatten function? I'm not sure that I see that as a real use case.

**Comment by nikitaeverywhere** [comment]
Thanks Jessie for your reply! Please check the linked issue — I explained
one of the use cases.

**Comment by nikitaeverywhere** [comment]
To bring one more solid argument,

From the pure JavaScript perspective, why for instance the library doesn't flatten Date object? Perhaps Buffer object? BigInt? You don't flatten those intentionally, right?

What if web standards bring more objects like these in the future? Perhaps you would need to update the library with more exceptions which is not that nice. Also, if we enumerate all objects which we should flatten and define how should we — it might be quite a big list. That was my first though when I started to dig in how flatten-like libraries work.

Thus I am wondering what is the typical use case for your library users ;)

P.S. The flatten for pure objects only turned to be just around 15 lines of code, so I switched to using it instead. Everything stated above is knowledge sharing.

**Comment by jessie-codes** [comment]
I'm not opposed to this change, but I would like to see some support from the community before making it as it would be a breaking change.

**Comment by nikitaeverywhere** [comment]
So do I. Thanks!

**Comment by kishanio** [comment]
@jessie-codes +1 to @ZitRos there's gotta be a way to not flatten things. Maybe a function in user passed options to test if the condition is met continue flattening for values or else stop for that particular node.

**Comment by kishanio** [comment]
My use case was Firestore Update which allows to update nested object using "dotted keys". Though it might have data types like Timestamps which doesn't need to get flatten.

**Comment by kishanio** [comment]
I wonder if we do something like this, `typeof <value>.constructor.name === Object`  makes sense? This will ignore date/primitives and cats as above.
