### ISSUE TITLE
Bug Report: Won't unflatten 3 level deep nested objects (will display the value as [Object])

### ISSUE THREAD

**Issue by narkiss-ibex** [jessie-codes/safe-flat#52]
**Describe the bug**
Unflatenning on a JSON that has 3 levels deep nesting objects, will result values to be saved as `[Object]` instead of the real value

**To Reproduce**
Run the following example
```javascript
const delimiter = "."
const data = {
  key1: {
      keyA: 'valueI'
  },
  key2: {
      keyB: 'valueII'
  },
  key3: { a: { b: { c: 2 } } }
}
let x = flatten(data, delimiter)
console.log(`x is:` , x)
let y = unflatten(x, delimiter)
console.log(`y is:` , y)
```

**Expected behavior**
The value on `y` should be:
```javascript
{
  key1: { keyA: 'valueI' },
  key2: { keyB: 'valueII' },
  key3: { a: { b: { c: 2 } } }
}
```
What is actually being generated:
```javascript
{
  key1: { keyA: 'valueI' },
  key2: { keyB: 'valueII' },
  key3: { a: { b: [Object] } }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/93870960/195066394-d1540305-d858-4268-b2c3-d9de4e5a653b.png)

Node v17.1.0

**Comment by jessie-codes** [comment]
Thanks for reporting this bug and providing a test case. I will investigate as soon as I can.

**Comment by narkiss-ibex** [comment]
It might be false, it seem it's just the browser not showing the data correctly. When using Node to write the content to a file, all the data is there, so the code works as intended - just not for displaying purposes on the console :)
